name: Workshop

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
  linter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: GLua Linter
        uses: TASSIA710/action-glua-lint@v1.1.4
        with:
          lint_maxScopeDepth: 99
          lint_deprecated: false
          lint_emptyBlocks: false
          lint_unusedParameters: false
          lint_unusedLoopVars: false
          lint_shadowing: false
          lint_inconsistentVariableStyle: false

 # Creates a GMA and publishes it to the Steam Workshop
  workshop-publish:
    needs: linter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Publish to Steam Workshop
        uses: Earu/GSW-action@V2.1
        with:
          account-name: ${{secrets.STEAM_NAME}}
          account-password: ${{secrets.STEAM_PASSWORD}}
          workshop-id: '2173212443'
          addon-path: ${{env.GITHUB_WORKSPACE}}